# Generated by Django 4.0.4 on 2022-08-14 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following2FollowersRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('follow_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rolls',
            name='products',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follow_model',
        ),
        migrations.AddField(
            model_name='profile',
            name='follow_relation',
            field=models.ManyToManyField(blank=True, through='profiles.Following2FollowersRelation', to='profiles.profile'),
        ),
        migrations.DeleteModel(
            name='Follower2FollowerRelation',
        ),
        migrations.DeleteModel(
            name='Rolls',
        ),
        migrations.AddField(
            model_name='following2followersrelation',
            name='followers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='following2followersrelation',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='profiles.profile'),
        ),
    ]
