# Generated by Django 4.0.4 on 2022-08-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_following2followersrelation_remove_rolls_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follow_relation',
            new_name='follow',
        ),
    ]
