# Generated by Django 4.0.4 on 2022-08-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_follow_relation_profile_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following2followersrelation',
            old_name='feedback',
            new_name='follow_reason',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='follow',
            new_name='follow_to',
        ),
    ]
